### PR TITLE
Change some metric names

### PR DESCRIPTION
**Pull request by qed-**
Following discussion of f41d9d9

### CODE REVIEW

**Comment by andrasm** [comment]
Sounds like this qualifies as a breaking change, though it would be a shame bumping the major version just for this. What about inactivating the current 1.0.0 package from nuget and release these changes as 1.1.0?

**Comment by qed-** [comment]
Fine by me.

**Comment by qed-** [comment]
Are you happy to integrate this @andrasm?

**Comment by andrasm** [comment]
right - merged + pushed to nuget as v1.1

**Pull request merged**
