### PR TITLE
Remove referenced assemblies from NuGet package

### PR DESCRIPTION
**Pull request by lakario**
The nuspec definition was incorrectly bundling all assemblies found in the Release directory. This bloats the package and should not have been included.

- Updated protobuf-net to 2.1
- Updated nunit to 3.6.
- Updated nuspec definition to not include referenced assemblies (oops)
- Updated assembly version from 1.3.4 to 1.3.6

### CODE REVIEW

**Comment by lakario** [comment]
@andrasm Can we release this?

**Comment by lakario** [comment]
@andrasm Are you available to release?

**Comment by andrasm** [comment]
Sorry not till the end of April; on vacation.

**Comment by lakario** [comment]
Alright, thanks! Enjoy your vacation.

**Comment by lakario** [comment]
I see you updated the repo, invalidating this change. Cheers.

**Pull request closed without merging**
