### PR TITLE
basic .netcore implementation

### PR DESCRIPTION
**Pull request by MihaMarkic**
I've added a .net core implementation by creating a new project and linked almost all files, except for MetricsServer (Kestrel implementation, by far the biggest change), DataContracts (removed Serializable attribute) and DotNetStatsCollector (removed openhandles, since those doesn't exist in .netcore).
Also referenced .netcore compatible Rx 3.0.0.
Created an unit test project, but couldn't run tests since "InternalVisibleTo" attribute doesn't seem to work at this time. Can you just make those types public instead?

Anyway, it seems working so far.

### CODE REVIEW

**Comment by andrasm** [comment]
thanks Miha - I'll take a look at this (and your other PR) over the weekend

**Comment by MihaMarkic** [comment]
Hi there. One thought. I didn't care at the moment about .netstandard version. It is set to 1.6 if I'm not mistaken. Perhaps you/me could lower that to make it more accessible.

**Comment by andrasm** [comment]
Hi Miha - I'll need more time with this PR, as far as I can see it's having problem with the travis build as well.

**Comment by ppreget** [comment]
Hi Miha - am also extremely keen on a .net core implementation; any update on this?

**Comment by MihaMarkic** [comment]
@ppreget Don't know about official, but feel free to try my fork.

**Comment by ppreget** [comment]
sounds good but where can I get your fork? link? repo?

**Comment by ppreget** [comment]
@MihaMarkic sorry, forget my comment, found it, thanks!

**Comment by sandersaares** [comment]
Closing this as obsolete - prometheus-net already includes .NET Core support by today.

**Pull request closed without merging**
