### PR TITLE
Add interfaces

### PR DESCRIPTION
**Pull request by qed-**
Adds ICounter, IGauge, IHistogram, ISummary implemented by both parent and child objects.
Also IMetricServer for completeness.

### CODE REVIEW

**Comment by andrasm** [comment]
thanks - will be available on nuget soon.

**Comment by qed-** [comment]
I think something's up with Nuget, the DLL is stamped 0.0.5.0 and doesnt have the DotNetStatsCollector class

**Comment by andrasm** [comment]
?

just tried it on a fresh project - it shows v0.0.8 with DotNetStatsCollector + the new interfaces available

**Comment by qed-** [comment]
Must have been a problem with my project, working now.

**Pull request merged**
