### PR TITLE
Feat/pushgateway

### PR DESCRIPTION
**Pull request by sderen**
Added basic pushgateway support. Refactored MetricServer and tester a bit along the way to support switching between MetricServer and MetricPusher easily and add more handlers in the future if needed.

### CODE REVIEW

**Comment by sstorie** [comment]
Was there any back-channel discussion on whether this PR would be accepted? I'm asking because I see this has been out there for 9 days with no comments, and it seems like a pretty important enhancement given the "pull" model Prometheus uses.

I'm starting to explore Prometheus as an option for instrumenting a variety of .NET desktop and WebAPI applications, and I think using the push gateway would be the proper route to take.

**Comment by pokemane** [comment]
@sstorie I think the author has just been busy, judging by the comments in #19 .  I'm interested in seeing this merged, too, but for now I'll likely be using the fork if I need the pushgateway.

**Comment by andrasm** [comment]
Sorry guys, I'll look into this sometime next week.

**Comment by sstorie** [comment]
I'm trying to run this PR locally by using the tester project and the `MetricPusherTester` against a push gateway running in a container, but am getting a a 500 error back from the gateway with this message in the body:

```
text format parsing error in line 1: invalid metric name
```

Here's a snapshot of what is POSTed to the push gateway:

```
﻿# HELP dotnet_totalmemory Total known allocated memory
# TYPE dotnet_totalmemory GAUGE
dotnet_totalmemory 1491408
# HELP dotnet_collection_errors_total Total number of errors that occured during collections
# TYPE dotnet_collection_errors_total COUNTER
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds
# TYPE process_start_time_seconds GAUGE
process_start_time_seconds 1470397895.78912
# HELP mySummary help text
# TYPE mySummary SUMMARY
mySummary_sum 6.00201343284082
mySummary_count 3
mySummary{quantile="0.5"} 0.214800252213515
mySummary{quantile="0.9"} 0.487213180627307
mySummary{quantile="0.99"} 0.487213180627307
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds
# TYPE process_cpu_seconds_total COUNTER
process_cpu_seconds_total 0.5928038
# HELP process_windows_private_bytes Process private memory size
# TYPE process_windows_private_bytes GAUGE
process_windows_private_bytes 21348352
# HELP myHistogram help text
# TYPE myHistogram HISTOGRAM
myHistogram_sum 0.85619075347492
myHistogram_count 3
myHistogram_bucket{le="0"} 0
myHistogram_bucket{le="0.2"} 1
myHistogram_bucket{le="0.4"} 3
myHistogram_bucket{le="0.6"} 3
myHistogram_bucket{le="0.8"} 3
myHistogram_bucket{le="0.9"} 3
myHistogram_bucket{le="+Inf"} 3
# HELP process_windows_open_handles Number of open handles
# TYPE process_windows_open_handles GAUGE
process_windows_open_handles 412
# HELP gauge help text
# TYPE gauge GAUGE
gauge 2.44228964412692
# HELP myCounter help text
# TYPE myCounter COUNTER
myCounter 2
myCounter{method="GET",endpoint="/"} 5
myCounter{method="POST",endpoint="/cancel"} 1
# HELP process_windows_num_threads Total number of threads
# TYPE process_windows_num_threads GAUGE
process_windows_num_threads 25
# HELP process_windows_working_set Process working set
# TYPE process_windows_working_set GAUGE
process_windows_working_set 30208000
# HELP process_windows_virtual_bytes Process virtual memory size
# TYPE process_windows_virtual_bytes GAUGE
process_windows_virtual_bytes 236007424
# HELP dotnet_collection_count_total GC collection count
# TYPE dotnet_collection_count_total COUNTER
dotnet_collection_count_total{generation="2"} 0
dotnet_collection_count_total{generation="0"} 0
dotnet_collection_count_total{generation="1"} 0
# HELP process_windows_processid Process ID
# TYPE process_windows_processid GAUGE
process_windows_processid 15200
```

Digging into this a bit more I noticed that when I copy the stream as a string from within Visual Studio, and paste it directly into Postman I see the following:

image

I also tried to examine this in Notepad++ where I can convert the strings easily to hex, and that showed me what was happening here.  If I convert two of the HELP lines to hex I see that the UTF-8 Byte Order Mark is being added to the beginning of the string:

image

I ended up needing to change the `AsciiFormatter.Format` method to specifically create an encoding that doesn't emit the BOM identifier (where the StreamWriter is created...):

```
        public static void Format(Stream destination, IEnumerable<MetricFamily> metrics)
        {
            var metricFamilys = metrics.ToArray();
            using (var streamWriter = new StreamWriter(destination, new UTF8Encoding(false)))
            {
                streamWriter.NewLine = "\n";
                foreach (var metricFamily in metricFamilys)
                {
                    WriteFamily(streamWriter, metricFamily);
                }
            }
        }
```

With this change I could get this PR working. Did you run into this at all while writing the PR?

**Comment by sderen** [comment]
Thanks for the catch! You are right about this. I was using this code in production for a while now, but I skipped #17 (commit ecd9f648a8c6ff012e04b5e9825a674a47ef21ca) which actually requires me to do additional work for the pushgateway. I will make sure it does not break anything else and update pr. Thanks again.

**Comment by sstorie** [comment]
I made a new PR for this simple change - https://github.com/andrasm/prometheus-net/pull/25

**Comment by andrasm** [comment]
Thank you guys for the PR, much appreciated. Both #24 and #25 are now part of 1.2-rc version on nuget.

**Pull request merged**
